<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \AppBundle\Entity\Post implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_id', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'category_id', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_title', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_desc', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_image', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_author', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_content', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_status', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'category_title', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_date'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_id', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'category_id', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_title', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_desc', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_image', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_author', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_content', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_status', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'category_title', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'post_date'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Post $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPostId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostId', []);

        return parent::getPostId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryId($categoryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryId', [$categoryId]);

        return parent::setCategoryId($categoryId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryId', []);

        return parent::getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostTitle($postTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostTitle', [$postTitle]);

        return parent::setPostTitle($postTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostTitle', []);

        return parent::getPostTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostDesc($postDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostDesc', [$postDesc]);

        return parent::setPostDesc($postDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostDesc', []);

        return parent::getPostDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostImage($postImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostImage', [$postImage]);

        return parent::setPostImage($postImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostImage', []);

        return parent::getPostImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostAuthor($postAuthor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostAuthor', [$postAuthor]);

        return parent::setPostAuthor($postAuthor);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostAuthor', []);

        return parent::getPostAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostContent($postContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostContent', [$postContent]);

        return parent::setPostContent($postContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostContent', []);

        return parent::getPostContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostStatus($postStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostStatus', [$postStatus]);

        return parent::setPostStatus($postStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostStatus', []);

        return parent::getPostStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostDate($postDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostDate', [$postDate]);

        return parent::setPostDate($postDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostDate', []);

        return parent::getPostDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryTitle($categoryTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryTitle', [$categoryTitle]);

        return parent::setCategoryTitle($categoryTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryTitle', []);

        return parent::getCategoryTitle();
    }

}
